version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: interviewPortal
      MYSQL_USER: interviewUser
      MYSQL_PASSWORD: Changeme1!
      MYSQL_ROOT_PASSWORD: Changeme1!
    # Done in prod to make a new db container using this volume
    # volumes:
    #  - .dbdata:/var/lib/mysql
    container_name: interviewPortal_db
  question_service:
    command: bash -c "go run models/migrations/main.go && go run main.go"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    expose:
      - 8080
      - 50052
    depends_on:
      - db
    container_name: interviewQuestionService