// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: set.proto

package question

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time        string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Type        uint32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedById uint32 `protobuf:"varint,4,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"`
	CreatedDate string `protobuf:"bytes,5,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate string `protobuf:"bytes,6,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Active      bool   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	QsName      string `protobuf:"bytes,8,opt,name=qs_name,json=qsName,proto3" json:"qs_name,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{0}
}

func (x *Set) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Set) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Set) GetCreatedById() uint32 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

func (x *Set) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *Set) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *Set) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Set) GetQsName() string {
	if x != nil {
		return x.QsName
	}
	return ""
}

type CreateSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *Set `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *CreateSetRequest) Reset() {
	*x = CreateSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetRequest) ProtoMessage() {}

func (x *CreateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetRequest.ProtoReflect.Descriptor instead.
func (*CreateSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSetRequest) GetSet() *Set {
	if x != nil {
		return x.Set
	}
	return nil
}

type CreateSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *Set `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *CreateSetResponse) Reset() {
	*x = CreateSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetResponse) ProtoMessage() {}

func (x *CreateSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetResponse.ProtoReflect.Descriptor instead.
func (*CreateSetResponse) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSetResponse) GetSet() *Set {
	if x != nil {
		return x.Set
	}
	return nil
}

type UpdateSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *Set   `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Id  uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateSetRequest) Reset() {
	*x = UpdateSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSetRequest) ProtoMessage() {}

func (x *UpdateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSetRequest) GetSet() *Set {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *UpdateSetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *Set `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *UpdateSetResponse) Reset() {
	*x = UpdateSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSetResponse) ProtoMessage() {}

func (x *UpdateSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSetResponse.ProtoReflect.Descriptor instead.
func (*UpdateSetResponse) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSetResponse) GetSet() *Set {
	if x != nil {
		return x.Set
	}
	return nil
}

type ListSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSetRequest) Reset() {
	*x = ListSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetRequest) ProtoMessage() {}

func (x *ListSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetRequest.ProtoReflect.Descriptor instead.
func (*ListSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{5}
}

type ListSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set []*Set `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty"`
}

func (x *ListSetResponse) Reset() {
	*x = ListSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetResponse) ProtoMessage() {}

func (x *ListSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetResponse.ProtoReflect.Descriptor instead.
func (*ListSetResponse) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{6}
}

func (x *ListSetResponse) GetSet() []*Set {
	if x != nil {
		return x.Set
	}
	return nil
}

type RetrieveSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RetrieveSetRequest) Reset() {
	*x = RetrieveSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSetRequest) ProtoMessage() {}

func (x *RetrieveSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSetRequest.ProtoReflect.Descriptor instead.
func (*RetrieveSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{7}
}

func (x *RetrieveSetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RetrieveSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set *Set `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *RetrieveSetResponse) Reset() {
	*x = RetrieveSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSetResponse) ProtoMessage() {}

func (x *RetrieveSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSetResponse.ProtoReflect.Descriptor instead.
func (*RetrieveSetResponse) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveSetResponse) GetSet() *Set {
	if x != nil {
		return x.Set
	}
	return nil
}

type DeleteSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSetRequest) Reset() {
	*x = DeleteSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetRequest) ProtoMessage() {}

func (x *DeleteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteSetResponse) Reset() {
	*x = DeleteSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetResponse) ProtoMessage() {}

func (x *DeleteSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSetResponse) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSetResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_set_proto protoreflect.FileDescriptor

var file_set_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x03,
	0x53, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x71, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x71, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2a, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22, 0x2b, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22, 0x3a, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74,
	0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x03, 0x73,
	0x65, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22,
	0x24, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03,
	0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x03, 0x73, 0x65, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x3b, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_set_proto_rawDescOnce sync.Once
	file_set_proto_rawDescData = file_set_proto_rawDesc
)

func file_set_proto_rawDescGZIP() []byte {
	file_set_proto_rawDescOnce.Do(func() {
		file_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_set_proto_rawDescData)
	})
	return file_set_proto_rawDescData
}

var file_set_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_set_proto_goTypes = []interface{}{
	(*Set)(nil),                 // 0: Set
	(*CreateSetRequest)(nil),    // 1: CreateSetRequest
	(*CreateSetResponse)(nil),   // 2: CreateSetResponse
	(*UpdateSetRequest)(nil),    // 3: UpdateSetRequest
	(*UpdateSetResponse)(nil),   // 4: UpdateSetResponse
	(*ListSetRequest)(nil),      // 5: ListSetRequest
	(*ListSetResponse)(nil),     // 6: ListSetResponse
	(*RetrieveSetRequest)(nil),  // 7: RetrieveSetRequest
	(*RetrieveSetResponse)(nil), // 8: RetrieveSetResponse
	(*DeleteSetRequest)(nil),    // 9: DeleteSetRequest
	(*DeleteSetResponse)(nil),   // 10: DeleteSetResponse
}
var file_set_proto_depIdxs = []int32{
	0, // 0: CreateSetRequest.set:type_name -> Set
	0, // 1: CreateSetResponse.set:type_name -> Set
	0, // 2: UpdateSetRequest.set:type_name -> Set
	0, // 3: UpdateSetResponse.set:type_name -> Set
	0, // 4: ListSetResponse.set:type_name -> Set
	0, // 5: RetrieveSetResponse.set:type_name -> Set
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_set_proto_init() }
func file_set_proto_init() {
	if File_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_set_proto_goTypes,
		DependencyIndexes: file_set_proto_depIdxs,
		MessageInfos:      file_set_proto_msgTypes,
	}.Build()
	File_set_proto = out.File
	file_set_proto_rawDesc = nil
	file_set_proto_goTypes = nil
	file_set_proto_depIdxs = nil
}
